LIBS:=`root-config --libs`
INCS:=`root-config --cflags`


esercizio4.0 : Esercizio4.0.cpp funzioni.h posizione.h
	g++ -o esercizio4.0 Esercizio4.0.cpp ${INCS} ${LIBS} 

clean:
	rm esercizio4.0
        
