esercizio1.3: main.o funzioni.o
	g++ main.o funzioni.o -o esercizio1.3

main.o: main.cpp funzioni.h
	g++ -c main.cpp -o main.o

funzioni.o : funzioni.cpp funzioni.h
	g++ -c funzioni.cpp -o funzioni.o

