LIBS:=`root-config --libs`
INCS:=`root-config --cflags`


esercizio4.1 : Esercizio4.1.cpp
	g++ -o esercizio4.1 Esercizio4.1.cpp ${INCS} ${LIBS} 

millikan: millikan.cpp
	g++ -o millikan millikan.cpp ${INCS} ${LIBS} 

clean:
	rm esercizio4.1
        
